server:
  port: 7722
  servlet.context-path: /icat/


springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG


spring:
  application:
    name: icatx-versioning-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
  data:
    mongodb:
      host: mongo
      port: 27017
      database: webprotege
      auto-index-creation: true
      uri: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://webprotege-local.edu/auth/webprotege # The issuer URL of your Keycloak realm
          jwk-set-uri: http://webprotege-local.edu/auth/realms/webprotege/protocol/openid-connect/certs # Optional, but speeds up token validation

webprotege:
  rabbitmq:
    requestqueue: icatx-versioning-service-queue
    responsequeue: icatx-versioning-service-response-queue
    timeout: 120000
  allowedOrigin: webprotege-local.edu
  versioning:
    location: /srv/versioning/

  minio:
    accessKey: webprotege
    endPoint: http://webprotege-local.edu:9000
    secretKey: webprotege
    uploads-bucket-name: webprotege-uploads
    versioning-bucket-name: webprotege-uploads

  directories:
    backup: /webprotege/backup

spring.security.oauth2:
  client:
    registration.keycloak:
      client-id: webprotege
      authorization-grant-type: authorization_code
      scope: openid
    provider.keycloak:
      issuer-uri: http://webprotege-local.edu/auth/realms/webprotege
      user-name-attribute: preferred_username
  resourceserver.jwt.issuer-uri: http://webprotege-local.edu/auth/realms/webprotege


mail:
  from:
    email: no-reply@sandbox331c6a2642cd4d8b83206859a546b672.mailgun.org
    name: iCatx emailing service
  destination-override: geo.soimu@whitebox.tech
  notification-default-signature: iCatx emailing service
  notification-mass-target:
  mailgun:
    base-url: https://api.mailgun.net/
    api-key: 97d0c0ceadb8c892f36db94b0d1b5ae2-0920befd-7e641ab1
    domain: sandbox331c6a2642cd4d8b83206859a546b672.mailgun.org
    send-emails: true